from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib import colors
from datetime import datetime
import config
import os

class PDFGenerator:
    """Generate professional PDF reports for safety violations"""
    
    def __init__(self):
        """Initialize PDF generator with styles"""
        self.styles = getSampleStyleSheet()
        
        # Custom styles
        self.title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=20,
            textColor='darkred',
            spaceAfter=30,
            alignment=TA_CENTER
        )
        
        self.heading_style = ParagraphStyle(
            'CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor='darkblue',
            spaceAfter=12,
            spaceBefore=12
        )
        
        self.body_style = ParagraphStyle(
            'CustomBody',
            parent=self.styles['Normal'],
            fontSize=11,
            spaceAfter=12
        )
    
    def generate_pdf(self, violation, report_text, image_path):
        """
        Generate PDF report
        
        Args:
            violation: Violation dictionary
            report_text: Generated report text from AI
            image_path: Path to violation screenshot
            
        Returns:
            Path to generated PDF
        """
        timestamp = violation['timestamp']
        filename = f"{timestamp.strftime('%Y%m%d_%H%M%S')}_incident_report.pdf"
        filepath = os.path.join(config.REPORTS_DIR, filename)
        
        # Create PDF document
        doc = SimpleDocTemplate(
            filepath,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18
        )
        
        # Container for PDF elements
        elements = []
        
        # Title
        title = Paragraph("SAFETY INCIDENT REPORT", self.title_style)
        elements.append(title)
        elements.append(Spacer(1, 0.2*inch))
        
        # Company Info
        company_info = f"""
        <b>{config.COMPANY_NAME}</b><br/>
        Site: {config.SITE_NAME}<br/>
        Location: {config.SITE_LOCATION}
        """
        elements.append(Paragraph(company_info, self.body_style))
        elements.append(Spacer(1, 0.3*inch))
        
        # Report Details Box
        report_details = f"""
        <b>Report ID:</b> {timestamp.strftime('%Y%m%d-%H%M%S')}<br/>
        <b>Date:</b> {timestamp.strftime('%B %d, %Y')}<br/>
        <b>Time:</b> {timestamp.strftime('%I:%M:%S %p')}<br/>
        <b>Generated:</b> {datetime.now().strftime('%B %d, %Y at %I:%M %p')}
        """
        elements.append(Paragraph(report_details, self.body_style))
        elements.append(Spacer(1, 0.3*inch))
        
        # Violation Summary
        elements.append(Paragraph("VIOLATION SUMMARY", self.heading_style))
        
        violation_summary = f"""
        <b>Type:</b> {violation['class_name'].replace('_', ' ').title()}<br/>
        <b>Description:</b> {violation['description']}<br/>
        <b>Detection Confidence:</b> {violation['confidence']*100:.1f}%<br/>
        <b>OSHA Regulation:</b> {violation['osha_regulation']}
        """
        elements.append(Paragraph(violation_summary, self.body_style))
        elements.append(Spacer(1, 0.3*inch))
        
        # Add violation image
        if image_path and os.path.exists(image_path):
            elements.append(Paragraph("VIOLATION EVIDENCE", self.heading_style))
            
            # Resize image to fit page
            img = Image(image_path, width=5*inch, height=3.75*inch)
            elements.append(img)
            elements.append(Spacer(1, 0.3*inch))
        
        # AI Generated Report
        elements.append(Paragraph("DETAILED INCIDENT ANALYSIS", self.heading_style))
        
        # Split report text into paragraphs
        report_paragraphs = report_text.strip().split('\n\n')
        for para_text in report_paragraphs:
            if para_text.strip():
                # Clean up the text
                clean_text = para_text.replace('\n', '<br/>')
                elements.append(Paragraph(clean_text, self.body_style))
        
        elements.append(Spacer(1, 0.3*inch))
        
        # Footer
        footer_text = """
        <i>This report was automatically generated by the AI Safety Compliance Officer system.
        A qualified safety professional should review and verify all incident details.</i>
        """
        elements.append(Paragraph(footer_text, self.body_style))
        
        # Build PDF
        doc.build(elements)
        
        print(f"PDF report generated: {filepath}")
        return filepath
    
    def generate_summary_report(self, violations_list):
        """
        Generate a daily/weekly summary report of all violations
        
        Args:
            violations_list: List of violation dictionaries
            
        Returns:
            Path to generated summary PDF
        """
        timestamp = datetime.now()
        filename = f"{timestamp.strftime('%Y%m%d')}_summary_report.pdf"
        filepath = os.path.join(config.REPORTS_DIR, filename)
        
        doc = SimpleDocTemplate(filepath, pagesize=letter)
        elements = []
        
        # Title
        title = Paragraph("DAILY SAFETY VIOLATIONS SUMMARY", self.title_style)
        elements.append(title)
        elements.append(Spacer(1, 0.2*inch))
        
        # Summary stats
        total_violations = len(violations_list)
        violation_types = {}
        for v in violations_list:
            vtype = v['class_name']
            violation_types[vtype] = violation_types.get(vtype, 0) + 1
        
        summary = f"""
        <b>Report Date:</b> {timestamp.strftime('%B %d, %Y')}<br/>
        <b>Total Violations:</b> {total_violations}<br/>
        <b>Site:</b> {config.SITE_NAME}
        """
        elements.append(Paragraph(summary, self.body_style))
        elements.append(Spacer(1, 0.3*inch))
        
        # Violation breakdown
        elements.append(Paragraph("VIOLATIONS BY TYPE", self.heading_style))
        
        for vtype, count in violation_types.items():
            line = f"• {vtype.replace('_', ' ').title()}: {count}"
            elements.append(Paragraph(line, self.body_style))
            
        elements.append(Spacer(1, 0.3*inch))

        # Detailed Table of Violations
        if violations_list:
            elements.append(Paragraph("DETAILED VIOLATION LOG", self.heading_style))
            
            # Table Header
            data = [['Time', 'Type', 'Description', 'Confidence']]
            
            # Table Data
            for v in violations_list:
                # Handle both dictionary and database object
                if isinstance(v, dict):
                    ts = v['timestamp']
                    cls_name = v['class_name']
                    desc = v['description']
                    conf = v['confidence']
                else:
                    ts = v.timestamp
                    cls_name = v.class_name
                    desc = v.description
                    conf = v.confidence

                data.append([
                    ts.strftime('%H:%M:%S'),
                    cls_name.replace('_', ' ').title(),
                    desc[:40] + "..." if len(desc) > 40 else desc,
                    f"{conf*100:.1f}%"
                ])

            # Create Table
            t = Table(data, colWidths=[1.2*inch, 1.5*inch, 3.0*inch, 1.0*inch])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
            ]))
            elements.append(t)
        
        # Build PDF
        doc.build(elements)
        
        print(f"Summary report generated: {filepath}")
        return filepath
