"""Yaoyao Structured Input Service — orchestrates OCR structured extraction
through the toolbox layer, with audit logging and human confirmation.

Sits between chitung-center API routes and agent-toolbox tool endpoints.
"""

from __future__ import annotations

import re
import uuid
import zipfile
from html import escape
from pathlib import Path
from typing import Any

from chitung_center.audit import audit_logger
from chitung_center.config import settings
from chitung_center.models import (
    YaoyaoConfirmRequest,
    YaoyaoExcelExportRequest,
    YaoyaoPageRenderRequest,
    YaoyaoStructuredDraftRequest,
    YaoyaoTemplateLoadRequest,
    YaoyaoTemplateSaveRequest,
)
from chitung_center.toolbox_client import toolbox_client


async def build_yaoyao_structured_draft(
    request: YaoyaoStructuredDraftRequest,
) -> dict[str, Any]:
    """Call toolbox to perform structured OCR extraction.

    Returns a draft with field candidates and a confirm_payload
    that must be accepted by a human before writing to the database.
    """
    audit_logger.write("yaoyao_draft_requested", {
        "file_path": request.file_path,
        "template_id": request.template_id,
        "case_id": request.case_id,
        "region_count": len(request.regions),
    })

    # Convert Pydantic regions to plain dicts for the toolbox call.
    regions_payload = [
        r.model_dump() if hasattr(r, "model_dump") else dict(r)
        for r in request.regions
    ]

    result = await toolbox_client.call_tool(
        "yaoyao_structured_extract",
        {
            "file_path": request.file_path,
            "regions": regions_payload,
            "page_index": request.page_index,
            "template_id": request.template_id,
            "case_id": request.case_id,
            "render_width": request.render_width,
            "render_height": request.render_height,
        },
        context={"source": "yaoyao_structured_service"},
    )

    ok = bool(result.get("ok"))
    if not ok:
        error = result.get("error", "Unknown toolbox error.")
        audit_logger.write("yaoyao_draft_failed", {
            "file_path": request.file_path,
            "error": error,
        })
        return {
            "ok": False,
            "message": f"Structured extraction failed: {error}",
            "requires_acceptance": False,
        }

    # Extract field candidates from toolbox result.
    raw_candidates = result.get("field_candidates", [])
    field_candidates = [
        {
            "field_name": fc.get("field_name", ""),
            "value": fc.get("value", ""),
            "confidence": fc.get("confidence", 0.0),
            "source_region": fc.get("source_region", ""),
            "page_number": fc.get("page_number", 1),
        }
        for fc in raw_candidates
        if isinstance(fc, dict)
    ]

    draft_id = result.get("draft_id", "")
    confirm_payload = result.get("confirm_payload", {})
    # Ensure the confirm payload has all needed fields.
    confirm_payload.update({
        "draft_id": draft_id,
        "template_id": request.template_id,
        "case_id": request.case_id,
    })

    audit_logger.write("yaoyao_draft_ready", {
        "draft_id": draft_id,
        "field_count": len(field_candidates),
        "page_count": result.get("page_count", 0),
    })

    return {
        "ok": True,
        "message": "Structured extraction draft ready. Fields must be confirmed before writing.",
        "draft_id": draft_id,
        "preview_image_path": result.get("preview_image_path"),
        "pages": result.get("pages", []),
        "field_candidates": field_candidates,
        "page_count": result.get("page_count", 0),
        "elapsed_seconds": result.get("elapsed_seconds", 0),
        "requires_acceptance": True,
        "confirm_payload": confirm_payload,
    }


async def render_yaoyao_page_preview(request: YaoyaoPageRenderRequest) -> dict[str, Any]:
    """Render one PDF page and return a browser-readable preview URL."""
    result = await toolbox_client.call_tool(
        "yaoyao_render_pdf_pages",
        {
            "file_path": request.file_path,
            "page_index": request.page_index,
            "render_width": request.render_width,
            "render_height": request.render_height,
        },
        context={"source": "yaoyao_structured_service"},
    )
    if not result.get("ok"):
        return {
            "ok": False,
            "message": f"PDF page render failed: {result.get('error', 'unknown error')}",
            "error": result.get("error"),
        }
    preview_path = str(result.get("preview_image_path") or "")
    return {
        **result,
        "preview_url": f"/api/yaoyao/preview-file?path={preview_path}" if preview_path else "",
    }


def resolve_yaoyao_preview_file(file_path: str) -> Path | None:
    """Resolve a local preview image generated by the toolbox."""
    if not file_path:
        return None
    path = Path(file_path)
    if not path.exists() or not path.is_file():
        return None
    if path.suffix.lower() not in {".jpg", ".jpeg", ".png", ".webp", ".bmp"}:
        return None
    return path


def export_yaoyao_excel(request: YaoyaoExcelExportRequest) -> dict[str, Any]:
    """Export OCR page rows to a lightweight XLSX workbook."""
    rows = request.rows or []
    region_names = [r.name for r in request.regions if r.name]
    if not region_names:
        region_names = _infer_region_names(rows)

    file_id = uuid.uuid4().hex
    file_name = _safe_excel_name(request.file_name or "ocr_result.xlsx")
    if not file_name.lower().endswith(".xlsx"):
        file_name = f"{file_name}.xlsx"
    output_dir = settings.chitung_data_dir / "yaoyao_exports"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{file_id}_{file_name}"
    _write_xlsx(output_path, rows, region_names)

    audit_logger.write("yaoyao_excel_exported", {
        "file_id": file_id,
        "row_count": len(rows),
        "column_count": len(region_names) + 1,
    })
    return {
        "ok": True,
        "file_id": file_id,
        "file_name": file_name,
        "output_path": str(output_path),
        "download_url": f"/api/yaoyao/export/{file_id}",
        "row_count": len(rows),
        "column_count": len(region_names) + 1,
    }


def resolve_yaoyao_export_file(file_id: str) -> Path | None:
    if not re.fullmatch(r"[A-Za-z0-9_-]{8,80}", file_id or ""):
        return None
    output_dir = settings.chitung_data_dir / "yaoyao_exports"
    if not output_dir.exists():
        return None
    for path in output_dir.glob(f"{file_id}_*.xlsx"):
        if path.is_file():
            return path
    return None


async def confirm_yaoyao_structured_draft(
    request: YaoyaoConfirmRequest,
) -> dict[str, Any]:
    """Confirm a structured extraction draft and write to form_records.

    All field values have been human-reviewed before this call.
    Writes via toolbox export_form_record and logs audit.
    """
    audit_logger.write("yaoyao_confirm_requested", {
        "draft_id": request.draft_id,
        "template_id": request.template_id,
        "case_id": request.case_id,
        "field_count": len(request.fields),
    })

    # Write confirmed fields to form_records via toolbox.
    template_id = request.template_id or "yaoyao_structured"
    result = await toolbox_client.call_tool(
        "export_form_record",
        {
            "template_id": template_id,
            "payload": {
                **request.fields,
                "_acceptance_notes": request.notes or "Accepted from Yaoyao structured input.",
                "_draft_id": request.draft_id,
                "_source": "yaoyao_structured_input",
            },
            "case_id": request.case_id,
            "output_path": None,
            "status": "accepted",
        },
        context={"source": "yaoyao_structured_service", "draft_id": request.draft_id},
    )

    ok = bool(result.get("ok"))
    audit_id = audit_logger.write("yaoyao_confirmed", {
        "draft_id": request.draft_id,
        "template_id": template_id,
        "case_id": request.case_id,
        "ok": ok,
        "field_count": len(request.fields),
    })

    if not ok:
        return {
            "ok": False,
            "message": "Failed to write confirmed fields to form_records.",
            "audit_id": audit_id,
        }

    # Extract record info from toolbox result.
    data = result.get("data", {}) if isinstance(result.get("data"), dict) else {}
    record_id = data.get("id") or data.get("record_id", "")
    output_path = data.get("output_path", "")

    return {
        "ok": True,
        "message": "Structured input confirmed and written to form_records.",
        "record_id": record_id,
        "output_path": output_path,
        "audit_id": audit_id,
    }


async def save_yaoyao_template(
    request: YaoyaoTemplateSaveRequest,
) -> dict[str, Any]:
    """Save an OCR recognition template via toolbox."""
    audit_logger.write("yaoyao_template_save", {
        "template_id": request.template_id,
        "name": request.name,
        "region_count": len(request.regions),
    })

    regions_payload = [
        r.model_dump() if hasattr(r, "model_dump") else dict(r)
        for r in request.regions
    ]

    result = await toolbox_client.call_tool(
        "yaoyao_save_template",
        {
            "regions": regions_payload,
            "rows": request.rows,
            "name": request.name,
            "template_id": request.template_id,
        },
    )
    return result


async def list_yaoyao_templates() -> dict[str, Any]:
    """List saved OCR templates via toolbox."""
    return await toolbox_client.call_tool("yaoyao_list_templates", {})


async def load_yaoyao_template(
    template_id: str,
) -> dict[str, Any]:
    """Load an OCR recognition template via toolbox."""
    result = await toolbox_client.call_tool(
        "yaoyao_load_template",
        {"template_id": template_id},
    )
    return result


def _infer_region_names(rows: list[dict[str, Any]]) -> list[str]:
    names: list[str] = []
    for row in rows:
        values = row.get("values") if isinstance(row.get("values"), dict) else {}
        for key in values:
            if key not in names:
                names.append(str(key))
    return names


def _safe_excel_name(value: str) -> str:
    name = Path(value).name.strip() or "ocr_result.xlsx"
    return re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", name)


def _write_xlsx(path: Path, rows: list[dict[str, Any]], region_names: list[str]) -> None:
    sheet_xml = _worksheet_xml(rows, region_names)
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", _content_types_xml())
        zf.writestr("_rels/.rels", _root_rels_xml())
        zf.writestr("xl/workbook.xml", _workbook_xml())
        zf.writestr("xl/_rels/workbook.xml.rels", _workbook_rels_xml())
        zf.writestr("xl/worksheets/sheet1.xml", sheet_xml)
        zf.writestr("xl/styles.xml", _styles_xml())


def _worksheet_xml(rows: list[dict[str, Any]], region_names: list[str]) -> str:
    table_rows: list[list[str]] = [["序號", *region_names]]
    for index, row in enumerate(rows, start=1):
        values = row.get("values") if isinstance(row.get("values"), dict) else {}
        page = row.get("pageNumber") or row.get("page_number") or row.get("page") or index
        table_rows.append([str(page), *[str(values.get(name, "")) for name in region_names]])

    row_xml = []
    for r_idx, row in enumerate(table_rows, start=1):
        cells = []
        for c_idx, value in enumerate(row, start=1):
            ref = f"{_col_name(c_idx)}{r_idx}"
            cells.append(f'<c r="{ref}" t="inlineStr"><is><t>{escape(value)}</t></is></c>')
        row_xml.append(f'<row r="{r_idx}">{"".join(cells)}</row>')
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
        f'<sheetData>{"".join(row_xml)}</sheetData>'
        '</worksheet>'
    )


def _col_name(index: int) -> str:
    name = ""
    while index:
        index, rem = divmod(index - 1, 26)
        name = chr(65 + rem) + name
    return name


def _content_types_xml() -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
        '<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
        '<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'
        '</Types>'
    )


def _root_rels_xml() -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'
        '</Relationships>'
    )


def _workbook_xml() -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        '<sheets><sheet name="OCR結果" sheetId="1" r:id="rId1"/></sheets>'
        '</workbook>'
    )


def _workbook_rels_xml() -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>'
        '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>'
        '</Relationships>'
    )


def _styles_xml() -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
        '<fonts count="1"><font><sz val="11"/><name val="Calibri"/></font></fonts>'
        '<fills count="1"><fill><patternFill patternType="none"/></fill></fills>'
        '<borders count="1"><border/></borders>'
        '<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>'
        '<cellXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/></cellXfs>'
        '</styleSheet>'
    )
